server:
  port: 8081


spring:
  application:
    #应用的名称，可选
    name: reggie_take_out
    #Redis相关配置
  redis:
    # 单机配置
    #host: localhost
    #port: 6379
    #database: 0  # Redis启动后默认提供了16个数据库，默认进入第0号数据库
    #jedis:  #spring data redis其实是对jedis的封装
    #Redis连接池配置
    #pool:
    # max-active: 8
    # max-wait: 1ms
    # max-idle: 8
    # min-idle: 0
    # 集群配置,使用时需要提前开启三个redis一主两从,再开启三个哨兵
      sentinel:
        master: mymaster
        nodes:
        - 127.0.0.1:26379  # ip:sentinel端口
        - 127.0.0.1:27001
        - 127.0.0.1:27002

  # spring shardingjdbc读写分离的配置，基于数据库的主从复制
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: yc12138**
      #从数据源172.21.66.191
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.27.77.231:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: yc12138**
    masterslave:
      #读写分离配置,负载均衡，加入有多个从库，挨个依次排队查询
      load-balance-algorithm-type: round_robin
      #最终的数据库名称
      name: dataSource
      #主数据库名称
      master-data-source-name: master
      #从数据库名称
      slave-data-source-names: slave
    props:
      sql:
        show: true  # 开启sql显示，默认为false,可以在控制台输出sql
  # 允许Bean定义覆盖，springshardingjdbc要创建数据源，druid连接池也要创建数据源，要允许bean定义覆盖才不会冲突
  main:
      allow-bean-definition-overriding: true




mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    #在映射实体或者属性时（这两种都会用到），将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    # 就是说以下true使得mybatisplus可以实现将数据库中的表和实体类对应起来：address_book表名  ---> AdderssBook实体类
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
    banner: false  # 设定springboot的标识不显示
reggie:
  path: D:\waimaipic\
logging:
  level:
    io.lettuce.core: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
